package: slice_columns
version: dev-0.0.1
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/statistics


requires:
  redaxo: '^5.11'
  packages:
  php:
    version: '>=7.1'

page:
  title: Slice-Columns
  perm: meinaddon[]
  icon: rex-icon fa-columns
  perm: admin[] 
  subpages:
    settings:  
      title: Einstellungen
      icon: rex-icon fa-cog
      perm: admin[] 
    help:
       title: translate:help
       subPath: README.md
       perm: admin[] 
  
default_config:
  number_columns: 12
  number_steps: 1
  min_width_column: 1
  definitions: '{
    "1": "col-sm-1",
    "2": "col-sm-2",
    "3": "col-sm-3",
    "4": "col-sm-4",
    "5": "col-sm-5",
    "6": "col-sm-6",
    "7": "col-sm-7",
    "8": "col-sm-8",
    "9": "col-sm-9",
    "10": "col-sm-10",
    "11": "col-sm-11",
    "12": "col-sm-12"
    }
    '


installer_ignore:
    - .git
